<a href="https://colab.research.google.com/github/Phantom6Paradise7/Data_Science_2026/blob/main/Numpy_and_Pandas_Day4%2B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,91, 25)
x = a.reshape(5,5)
mean_row = np.mean(x, axis = 1)
# finding the mean of the matrix row wise and the column wise
print(mean_row)
mean_column = np.mean(x, axis = 0)
print(mean_column)
#replacing all even elements with -1
replace = np.where(x % 2 == 0, -1, x)
print(replace)
# sort the array row wise and the coloumn wise
sort_row = np.sort(replace, axis = 1)
print(sort_row)
sort_column = np.sort(replace, axis = 0)
print(sort_column)
# find the sum of sorted row and sorted column
sorted_row_sum = np.sum(sort_row, axis = 1)
print(sorted_row_sum)
sorted_column_sum = np.sum(sort_column, axis = 0)
print(sorted_column_sum)
# for counting the number of -ve the each coloumns
neg_count = np.sum(replace < 0, axis = 0)
print(neg_count)
neg_col_count = np.sum(np.where(replace < 0, 1, 0), axis = 0)
print(neg_col_count)

[43.  50.2 61.8 39.  46.6]
[42.8 52.6 59.8 52.2 33.2]
[[-1 -1 85 49 35]
 [-1 -1 -1 -1 55]
 [-1 -1 81 -1 -1]
 [-1 61  9 23 -1]
 [-1 -1 -1 55 -1]]
[[-1 -1 35 49 85]
 [-1 -1 -1 -1 55]
 [-1 -1 -1 -1 81]
 [-1 -1  9 23 61]
 [-1 -1 -1 -1 55]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1  9 23 -1]
 [-1 -1 81 49 35]
 [-1 61 85 55 55]]
[167  51  77  91  51]
[ -5  57 173 125  87]
[5 4 2 2 3]
[5 4 2 2 3]

In [ ]:
stocks = np.random.randint(20,80, size = (5,5))
print(stocks)
demand = np.random.randint(20,80, size = (5,5))
print(demand)
remaining_stock = stocks - demand
print(remaining_stock)
new_stock = np.where(remaining_stock < 0, 0, remaining_stock)
print(new_stock)
total_shortage = np.sum(np.where(remaining_stock < 0, remaining_stock * -1, 0), axis = 0)
print(total_shortage)
products_with_zero_stock = np.sum(np.where(total_shortage == 0, 1, 0), axis = 0)
print(products_with_zero_stock)
sort_based_on_remaining_stock = np.sort(remaining_stock, axis = 1)
print(sort_based_on_remaining_stock)
sort_based_on_remaining_stock = np.sort(remaining_stock, axis = 0)
print(sort_based_on_remaining_stock)

[[72 40 34 36 77]
 [20 37 21 77 55]
 [75 32 42 43 40]
 [73 37 70 65 20]
 [67 40 32 31 43]]
[[32 40 53 23 37]
 [60 64 25 26 21]
 [29 47 67 50 48]
 [75 33 70 67 50]
 [38 77 21 40 30]]
[[ 40   0 -19  13  40]
 [-40 -27  -4  51  34]
 [ 46 -15 -25  -7  -8]
 [ -2   4   0  -2 -30]
 [ 29 -37  11  -9  13]]
[[40  0  0 13 40]
 [ 0  0  0 51 34]
 [46  0  0  0  0]
 [ 0  4  0  0  0]
 [29  0 11  0 13]]
[42 79 48 18 38]
0
[[-19   0  13  40  40]
 [-40 -27  -4  34  51]
 [-25 -15  -8  -7  46]
 [-30  -2  -2   0   4]
 [-37  -9  11  13  29]]
[[-40 -37 -25  -9 -30]
 [ -2 -27 -19  -7  -8]
 [ 29 -15  -4  -2  13]
 [ 40   0   0  13  34]
 [ 46   4  11  51  40]]

# ***Pandas***

In [ ]:
import pandas as pd

In [ ]:
file_ = pd.read_csv("./student_data.csv", sep = ',')

print(file_)
print(file_.head())
print(file_.tail())

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]
   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

In [ ]:
dic = {
    'name': ['Tom', 'Nick', 'Krish', 'Jack'],
    'age': [20, 21, 19, 18],
    "roll": [1,2,3,4]
}
df = pd.DataFrame(dic)
print(df)
display(df)

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

In [ ]:
dfo = pd.read_csv("./student_data.csv", sep = ',')
#print(dfo)
a = dfo.tail(3) #
print(a)
b = dfo.head(4) # tells the
print(b)
c = dfo.shape #tells the no. of rows and column
print(c)
dfo.info() #tells and provides the metadata of the file

      study_hours  attendance  sleep_hours  internet_usage  \
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed
   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
(10000, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [ ]:
dfo.describe()

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [ ]:
dfo.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [ ]:
dfo[['study_hours','internet_usage']]

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

In [ ]:
dfo.loc[dfo['study_hours'] == 11]
dfo.iloc
# print(df.head(3))
#print(df.tail(3)) # last 3 values
#print(df.shape) # rows and columns
#print(df.info) # dataframe metadata(file info - columns,datatypes,filetype)
#df.describe() - #statstical summary(mean.med,quartiles,std,min,max)
#df.columns - name of columns
#df.index
#df[['study_hours','internet_usage']] - to acess columns
#df.iloc[0] - # to acess rows
df.iloc[0:5]
df.loc[df['study_hours']==11,['study_hours']]
df.loc[df['study_hours'] == 11, ['study_hours', 'sleep_hours']].iloc[4: 8]

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [ ]:
#iloc works on index
#and loc works on label

In [ ]:
df=pd.read_csv('student_data.csv')
df[df['assignments_completed']  >3 ]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df["age"] = 20

In [ ]:
df = pd.read_csv('student_data.csv')
df = df.rename(columns = {'assignments_completed' : 'assign_completed'})
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
df.rename(columns={"assignments_completed":'assign completed'} , inplace =True)
df

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df.drop(columns=['placement_status'])

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score
0,7,56,8,7,10,62,100.00
1,4,69,5,3,8,56,100.00
2,11,60,7,6,10,45,100.00
3,8,99,9,8,4,55,90.17
4,5,52,8,6,8,40,78.82
...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31
9996,7,98,6,9,4,87,100.00
9997,10,44,8,5,10,37,95.94
9998,10,75,7,5,8,52,88.61
9999,2,70,6,11,16,52,78.96

In [ ]:
df.dropna()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df.sort_values(by='study_hours')

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
979,1,99,9,7,14,76,94.92,Placed
9191,1,92,9,1,9,70,98.52,Placed
9190,1,57,6,4,13,39,81.96,Placed
9178,1,49,7,4,10,76,64.86,Not Placed
9175,1,72,6,2,19,62,82.22,Placed
...,...,...,...,...,...,...,...,...
5446,11,57,4,1,2,83,100.00,Placed
5447,11,95,7,11,14,43,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

In [ ]:
df.sort_index()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
import numpy as np
dct = {
    'name' : ['Anu', 'Riya', 'Suga', 'Jimin'],
    'age' : [22, 25, 32, 30],
    'roll' : [1, np.nan, 3, 4]
}

dF = pd.DataFrame(dct)
dF

    name  age  roll
0    Anu   22   1.0
1   Riya   25   NaN
2   Suga   32   3.0
3  Jimin   30   4.0

In [ ]:
dF.dropna()

    name  age  roll
0    Anu   22   1.0
2   Suga   32   3.0
3  Jimin   30   4.0